name: Check scss files

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
        env:
          CI: true
